"""Initial migration.

Revision ID: 1fb973c28545
Revises: 
Create Date: 2024-07-25 12:05:48.609226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb973c28545'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_structure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_structure_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_structure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_structure_name'))

    op.drop_table('table_structure')
    # ### end Alembic commands ###
